name: orpheus-tts
channels:
  - defaults
dependencies:
  - python=3.12.9
  - pip
  - pip:
      - click==8.1.8
      - datasets==3.4.1
      - huggingface-hub==0.29.3
      - librosa==0.11.0
      - numpy==1.26.4
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - orpheus-speech==0.1.0
      - peft==0.15.0 # for LoRA?
      - python-dotenv==1.0.1
      - snac==1.2.1
      - soundfile==0.13.1
      - tokenizers==0.21.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.50.0
      - vllm==0.7.3
